import { useState } from 'react';
import { View,Text,TextInput,TouchableOpacity,StyleSheet,ScrollView,Image,ActivityIndicator } from 'react-native';
import { Camera,Check,AlertCircle,User } from 'lucide-react-native';
import { useNav } from '@/navigation/nav';
import { useAuth } from '@/providers/AuthProvider';
import { updateProfile } from '@/lib/profiles';
import { pickAndUpload } from '@/lib/storage';
import { useLanguage } from '@/providers/LanguageProvider';
export function EditProfileScreen(){const {goBack}=useNav();const {profile,refreshProfile}=useAuth();const {t}=useLanguage();const [displayName,setDisplayName]=useState(profile?.display_name||'');const [bio,setBio]=useState(profile?.bio||'');const [avatarUrl,setAvatarUrl]=useState<string|null>(profile?.avatar_url||null);const [uploading,setUploading]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);const changeAvatar=async()=>{if(!profile?.id)return;setUploading(true);try{const url=await pickAndUpload('avatars',profile.id,{square:true});if(url)setAvatarUrl(url);}catch(e:any){setError(e?.message||'Unable to upload photo.');}finally{setUploading(false);}};const save=async()=>{setError(null);if(!profile?.id)return;if(!displayName.trim())return setError(t('displayName'));setSaving(true);try{await updateProfile(profile.id,{display_name:displayName.trim(),bio:bio.trim()||null as any,avatar_url:avatarUrl});await refreshProfile();goBack();}catch(e:any){setError(e?.message||'Unable to save profile.');setSaving(false);}};const initial=(displayName||'T').charAt(0).toUpperCase();return <ScrollView style={styles.scroll} contentContainerStyle={styles.container}><View style={styles.avatarSection}><TouchableOpacity onPress={changeAvatar}>{avatarUrl?<Image source={{uri:avatarUrl}} style={styles.avatarImg}/>:<View style={styles.avatar}><Text style={styles.avatarText}>{initial}</Text></View>}<View style={styles.avatarEdit}>{uploading?<ActivityIndicator color="#fff"/>:<Camera size={18} color="#fff"/>}</View></TouchableOpacity><Text style={styles.avatarHint}>{t('touchToChangePhoto')}</Text></View><Text style={styles.label}>{t('displayName')}</Text><View style={styles.inputWrap}><User size={20} color="#9CA3AF"/><TextInput style={styles.input} placeholder={t('displayNamePlaceholder')} value={displayName} onChangeText={setDisplayName}/></View><Text style={styles.label}>{t('bio')}</Text><TextInput style={[styles.inputPlain,styles.textarea]} placeholder={t('bioPlaceholder')} value={bio} onChangeText={setBio} multiline/>{error&&<View style={styles.errorBox}><AlertCircle size={16} color="#DC2626"/><Text style={styles.errorText}>{error}</Text></View>}<TouchableOpacity style={styles.saveBtn} onPress={save} disabled={saving}>{saving?<ActivityIndicator color="#fff"/>:<><Check size={18} color="#fff"/><Text style={styles.saveBtnText}>{t('saveChanges')}</Text></>}</TouchableOpacity><TouchableOpacity style={styles.cancelBtn} onPress={goBack}><Text style={styles.cancelBtnText}>{t('cancel')}</Text></TouchableOpacity></ScrollView>}
const styles=StyleSheet.create({scroll:{flex:1,backgroundColor:'#F8FAFC'},container:{padding:20,paddingBottom:60,gap:8},avatarSection:{alignItems:'center',marginBottom:12,gap:8},avatar:{width:110,height:110,borderRadius:32,backgroundColor:'#FF9F43',alignItems:'center',justifyContent:'center'},avatarImg:{width:110,height:110,borderRadius:32},avatarText:{fontSize:40,fontWeight:'800',color:'#fff'},avatarEdit:{position:'absolute',bottom:0,right:0,width:36,height:36,borderRadius:18,backgroundColor:'#2D7FF9',alignItems:'center',justifyContent:'center'},avatarHint:{fontSize:13,color:'#6B7280'},label:{fontSize:14,fontWeight:'700',color:'#374151',marginTop:12},inputWrap:{flexDirection:'row',alignItems:'center',backgroundColor:'#fff',borderWidth:1,borderColor:'#E5E7EB',borderRadius:16,height:56,paddingHorizontal:14,gap:8},input:{flex:1,fontSize:16,color:'#1F2937'},inputPlain:{backgroundColor:'#fff',borderWidth:1,borderColor:'#E5E7EB',borderRadius:16,padding:14,fontSize:16,color:'#1F2937'},textarea:{height:100,textAlignVertical:'top'},errorBox:{flexDirection:'row',gap:8,backgroundColor:'#FEF2F2',padding:12,borderRadius:14},errorText:{flex:1,color:'#DC2626'},saveBtn:{flexDirection:'row',justifyContent:'center',alignItems:'center',gap:8,backgroundColor:'#2D7FF9',paddingVertical:16,borderRadius:18,marginTop:20},saveBtnText:{color:'#fff',fontSize:16,fontWeight:'700'},cancelBtn:{alignItems:'center',paddingVertical:14},cancelBtnText:{color:'#6B7280',fontWeight:'600'}});
