import { useState } from 'react';
import { View,Text,TextInput,TouchableOpacity,StyleSheet,Platform,KeyboardAvoidingView,ScrollView,ActivityIndicator } from 'react-native';
import { ChevronLeft,Mail,Lock,Eye,EyeOff,AlertCircle } from 'lucide-react-native';
import { FadeIn } from '@/components/FadeIn';
import { signIn } from '@/lib/auth';
import { useLanguage } from '@/providers/LanguageProvider';
interface LoginScreenProps{onBack:()=>void;onForgot:()=>void;onGoRegister:()=>void;}
export function LoginScreen({onBack,onForgot,onGoRegister}:LoginScreenProps){const {t}=useLanguage();const [showPass,setShowPass]=useState(false);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState<string|null>(null);const submit=async()=>{setError(null);if(!email.trim()||!password)return setError(`${t('email')} and ${t('password')}`);setLoading(true);try{await signIn(email,password);}catch(e:any){const msg=e?.message||'Unable to sign in.';setError(msg.includes('Invalid login')?'Invalid email or password.':msg);}finally{setLoading(false);}};return <KeyboardAvoidingView style={styles.container} behavior={Platform.OS==='ios'?'padding':undefined}><View style={styles.topBar}><TouchableOpacity onPress={onBack} style={styles.backBtn} accessibilityLabel={t('back')}><ChevronLeft size={22} color="#374151"/></TouchableOpacity></View><ScrollView contentContainerStyle={styles.body}><FadeIn><Text style={styles.title}>{t('welcomeBack')}</Text><Text style={styles.subtitle}>{t('signInToContinue')}</Text></FadeIn><View style={styles.form}><Text style={styles.label}>{t('email')}</Text><View style={styles.inputWrap}><Mail size={20} color="#9CA3AF"/><TextInput style={styles.input} placeholder="you@example.com" value={email} onChangeText={setEmail}/></View><Text style={styles.label}>{t('password')}</Text><View style={styles.inputWrap}><Lock size={20} color="#9CA3AF"/><TextInput style={styles.input} placeholder="••••••••" secureTextEntry={!showPass} value={password} onChangeText={setPassword}/><TouchableOpacity onPress={()=>setShowPass(s=>!s)}>{showPass?<EyeOff size={20} color="#9CA3AF"/>:<Eye size={20} color="#9CA3AF"/>}</TouchableOpacity></View>{error&&<View style={styles.error}><AlertCircle size={16} color="#DC2626"/><Text style={styles.errorText}>{error}</Text></View>}<TouchableOpacity onPress={onForgot}><Text style={styles.forgot}>{t('forgotPassword')}</Text></TouchableOpacity><TouchableOpacity style={styles.primary} onPress={submit} disabled={loading}>{loading?<ActivityIndicator color="#fff"/>:<Text style={styles.primaryText}>{t('signIn')}</Text>}</TouchableOpacity></View><View style={styles.register}><Text style={styles.muted}>{t('noAccount')} </Text><TouchableOpacity onPress={onGoRegister}><Text style={styles.link}>{t('register')}</Text></TouchableOpacity></View></ScrollView></KeyboardAvoidingView>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#F8FAFC'},topBar:{paddingTop:Platform.OS==='ios'?56:28,paddingHorizontal:20},backBtn:{width:40,height:40,borderRadius:20,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},body:{padding:24},title:{fontSize:30,fontWeight:'800',color:'#1F2937'},subtitle:{marginTop:8,fontSize:15,color:'#6B7280'},form:{marginTop:32,gap:12},label:{fontSize:14,fontWeight:'600',color:'#374151'},inputWrap:{flexDirection:'row',alignItems:'center',gap:10,backgroundColor:'#fff',borderWidth:1,borderColor:'#E5E7EB',borderRadius:18,height:56,paddingHorizontal:16},input:{flex:1,fontSize:16},error:{flexDirection:'row',gap:8,backgroundColor:'#FEF2F2',padding:12,borderRadius:14},errorText:{flex:1,color:'#DC2626'},forgot:{alignSelf:'flex-end',color:'#2D7FF9',fontWeight:'600'},primary:{backgroundColor:'#2D7FF9',paddingVertical:16,borderRadius:18,alignItems:'center',marginTop:8},primaryText:{color:'#fff',fontWeight:'600',fontSize:16},register:{flexDirection:'row',justifyContent:'center',marginTop:28},muted:{color:'#6B7280'},link:{color:'#2D7FF9',fontWeight:'700'}});
