import { useEffect,useState,useCallback } from 'react';
import { View,Text,Image,TouchableOpacity,StyleSheet,ScrollView,ActivityIndicator } from 'react-native';
import { Settings as SettingsIcon,Pencil,LogOut,Globe,MapPin,Award,Trophy,Camera,Calendar } from 'lucide-react-native';
import { FadeIn } from '@/components/FadeIn';
import { useNav } from '@/navigation/nav';
import { useAuth } from '@/providers/AuthProvider';
import { getProfileStats,type ProfileStats } from '@/lib/profiles';
import { signOut } from '@/lib/auth';
import { useLanguage } from '@/providers/LanguageProvider';
export function ProfileScreen(){const {navigate}=useNav();const {profile,user}=useAuth();const {t}=useLanguage();const [stats,setStats]=useState<ProfileStats>({pins:0,cities:0,countries:0});const [loading,setLoading]=useState(true);const [loggingOut,setLoggingOut]=useState(false);const load=useCallback(async()=>{if(!profile?.id)return;try{setStats(await getProfileStats(profile.id));}catch{}finally{setLoading(false);}},[profile?.id]);useEffect(()=>{load();},[load]);const handleLogout=async()=>{setLoggingOut(true);try{await signOut();}catch{setLoggingOut(false);}};const displayName=profile?.display_name||user?.email?.split('@')[0]||t('traveler');const memberYear=profile?.created_at?new Date(profile.created_at).getFullYear():new Date().getFullYear();const initial=displayName.charAt(0).toUpperCase();const items=[{label:t('countries'),value:stats.countries,icon:Globe},{label:t('cities'),value:stats.cities,icon:MapPin},{label:t('pins'),value:stats.pins,icon:Camera},{label:t('badges'),value:0,icon:Trophy}];return <ScrollView style={styles.scroll} contentContainerStyle={styles.container}><View style={styles.cover}/><View style={styles.avatarWrap}>{profile?.avatar_url?<Image source={{uri:profile.avatar_url}} style={styles.avatarImg}/>:<View style={styles.avatar}><Text style={styles.avatarText}>{initial}</Text></View>}<View style={styles.avatarBadge}><Award size={14} color="#fff"/></View></View><View style={styles.nameSection}><FadeIn><Text style={styles.name}>{displayName}</Text></FadeIn><View style={styles.chipRow}><View style={styles.levelChip}><Award size={12} color="#0F766E"/><Text style={styles.levelChipText}>{t('explorer')}</Text></View><View style={styles.memberChip}><Calendar size={12} color="#4B5563"/><Text style={styles.memberChipText}>{t('memberSince')} {memberYear}</Text></View></View>{profile?.bio?<Text style={styles.bio}>{profile.bio}</Text>:null}</View><View style={styles.statsGrid}>{items.map(s=>{const Icon=s.icon;return <View key={s.label} style={styles.statCard}><Icon size={20} color="#2D7FF9"/><Text style={styles.statValue}>{loading?'—':s.value}</Text><Text style={styles.statLabel}>{s.label}</Text></View>;})}</View><View style={styles.buttons}><TouchableOpacity style={styles.primaryBtn} onPress={()=>navigate('editProfile')}><Pencil size={16} color="#fff"/><Text style={styles.primaryBtnText}>{t('editProfileAction')}</Text></TouchableOpacity><TouchableOpacity style={styles.secondaryBtn} onPress={()=>navigate('settings')}><SettingsIcon size={16} color="#1F2937"/><Text style={styles.secondaryBtnText}>{t('settingsAction')}</Text></TouchableOpacity><TouchableOpacity style={styles.logoutBtn} onPress={handleLogout} disabled={loggingOut}>{loggingOut?<ActivityIndicator color="#EF4444"/>:<><LogOut size={16} color="#EF4444"/><Text style={styles.logoutBtnText}>{t('logOut')}</Text></>}</TouchableOpacity></View></ScrollView>}
const styles=StyleSheet.create({scroll:{flex:1,backgroundColor:'#F8FAFC'},container:{paddingBottom:120},cover:{height:128,backgroundColor:'#2D7FF9'},avatarWrap:{paddingHorizontal:20,marginTop:-48},avatar:{width:96,height:96,borderRadius:28,backgroundColor:'#FF9F43',borderWidth:4,borderColor:'#fff',alignItems:'center',justifyContent:'center'},avatarImg:{width:96,height:96,borderRadius:28},avatarText:{fontSize:32,fontWeight:'800',color:'#fff'},avatarBadge:{position:'absolute',bottom:4,right:24,width:28,height:28,borderRadius:14,backgroundColor:'#3EC7B8',borderWidth:2,borderColor:'#fff',alignItems:'center',justifyContent:'center'},nameSection:{paddingHorizontal:20,paddingTop:12},name:{fontSize:24,fontWeight:'800',color:'#1F2937'},chipRow:{flexDirection:'row',gap:8,marginTop:6,flexWrap:'wrap'},levelChip:{flexDirection:'row',alignItems:'center',gap:4,backgroundColor:'#CCFBF1',paddingHorizontal:10,paddingVertical:4,borderRadius:999},levelChipText:{fontSize:12,fontWeight:'600',color:'#0F766E'},memberChip:{flexDirection:'row',alignItems:'center',gap:4,backgroundColor:'#F3F4F6',paddingHorizontal:10,paddingVertical:4,borderRadius:999},memberChipText:{fontSize:12,fontWeight:'600',color:'#4B5563'},bio:{marginTop:10,fontSize:14,color:'#4B5563'},statsGrid:{flexDirection:'row',paddingHorizontal:20,paddingTop:20,gap:8},statCard:{flex:1,alignItems:'center',backgroundColor:'#fff',borderRadius:18,padding:12},statValue:{fontSize:20,fontWeight:'800',color:'#1F2937'},statLabel:{fontSize:10,color:'#6B7280'},buttons:{paddingHorizontal:20,paddingTop:24,gap:12},primaryBtn:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,backgroundColor:'#2D7FF9',paddingVertical:14,borderRadius:18},primaryBtnText:{fontSize:16,fontWeight:'600',color:'#fff'},secondaryBtn:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,backgroundColor:'#fff',paddingVertical:14,borderRadius:18},secondaryBtnText:{fontSize:16,fontWeight:'600',color:'#1F2937'},logoutBtn:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,backgroundColor:'rgba(239,68,68,0.1)',paddingVertical:14,borderRadius:18},logoutBtnText:{fontSize:16,fontWeight:'600',color:'#EF4444'}});
